name: commandline_interface
description: CLI. Minimalist.
repository: https://github.com/monki1/commandline_interface_flutter.git
version: 0.0.6

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:
